### ISSUE TITLE
Invalid MantaUser results in 500 Internal Server Error 

### ISSUE THREAD

**Issue by cburroughs** [joyent/java-manta#123]
``` java
        ConfigContext defaultConfig = new DefaultsConfigContext();
        ConfigContext customConfig = new StandardConfigContext()
            .setMantaKeyId("some placeholder string")
            .setMantaUser("MY USERNAME");

        ConfigContext config = new ChainedConfigContext(defaultConfig, customConfig);

        MantaClient client = new MantaClient(config);
```

Results in 

```
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.joyent.manta.exception.MantaClientHttpResponseException: 500 Internal Server Error (request: 6011f622-d259-4a66-84fe-712be5927396) - [InternalError] an unexpected error occurred
    at com.joyent.manta.client.HttpHelper.buildException(HttpHelper.java:449)
    at com.joyent.manta.client.HttpHelper.executeAndCloseRequest(HttpHelper.java:380)
    at com.joyent.manta.client.MantaClient.putDirectory(MantaClient.java:1256)
    at com.joyent.manta.client.MantaClient.putDirectory(MantaClient.java:1308)
    at com.joyent.manta.client.MantaClient.putDirectory(MantaClient.java:1275)
    at com.joyent.manta.client.multipart.MantaMultipartManager.initiateUpload(MantaMultipartManager.java:219)
    at com.joyent.manta.client.multipart.MantaMultipartManager.initiateUpload(MantaMultipartManager.java:183)
    at com.joyent.example.Foo.main(Foo.java:28)
    ... 6 more
Caused by: com.google.api.client.http.HttpResponseException: 500 Internal Server Error
{"code":"InternalError","message":"an unexpected error occurred"}
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1070)
    at com.joyent.manta.client.HttpHelper.executeAndCloseRequest(HttpHelper.java:374)
```

I'm unsure if this is a client problem, a server problem, or if this is desired behavior for an invalid (as opposed to non-existant) user.

**Comment by nairashwin952013** [comment]
@dekobon When I reproduced this issue and ran the following test class:
```
package com.joyent.invaliduser;

import com.joyent.manta.client.MantaClient;
import com.joyent.manta.config.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.util.UUID;

public class InvalidUserApplication {
    private static final Logger LOG = LoggerFactory.getLogger(InvalidUserApplication.class);

    private static final String TEST_DATA = "EPISODEII_IS_BEST_EPISODE";

    public static void main(final String[] args) throws RuntimeException, IOException {
        System.setProperty("manta.dumpConfig", "true");
        EnvVarConfigContext authConfig = new EnvVarConfigContext();
        ConfigContext config = new ChainedConfigContext(
                new StandardConfigContext()
                        .setMantaKeyId("some placeholder string")
                        .setMantaUser("MY USERNAME"),
                new DefaultsConfigContext()

        );

        try(MantaClient client = new MantaClient(config)) {
            final String name = UUID.randomUUID().toString();
            final String path = config.getMantaUser()+ "/stor/" + name;
            client.put(path, TEST_DATA);

        } catch (RuntimeException e) {
            LOG.error("Invalid Manta User specified", e);
        }
    }
}
```
StackTrace:
```
[main] DEBUG com.joyent.manta.client.crypto.ExternalSecurityProviderLoader - PKCS11 NSS provider was loaded - native crypto support available
[main] INFO com.joyent.manta.client.crypto.ExternalSecurityProviderLoader - Security provider chosen for CSE: SunPKCS11-NSS version 1.8 
[main] DEBUG com.joyent.manta.client.MantaClient - Preferred Security Provider: SunPKCS11-NSS version 1.8
[main] ERROR com.joyent.invaliduser.InvalidUserApplication - Invalid Manta User specified
com.joyent.manta.exception.ConfigurationException: Given fingerprint some placeholder string does not match expected key ```EnvKeyValue```
Exception Context:
	[1:mantaSdkVersion=3.3.1-SNAPSHOT]
---------------------------------
	at com.joyent.manta.config.KeyPairFactory.createKeyPair(KeyPairFactory.java:92)
	at com.joyent.manta.config.AuthAwareConfigContext.doLoad(AuthAwareConfigContext.java:104)
	at com.joyent.manta.config.AuthAwareConfigContext.reload(AuthAwareConfigContext.java:86)
	at com.joyent.manta.config.AuthAwareConfigContext.<init>(AuthAwareConfigContext.java:62)
	at com.joyent.manta.client.MantaClient.<init>(MantaClient.java:262)
	at com.joyent.manta.client.MantaClient.<init>(MantaClient.java:211)
	at com.joyent.manta.client.MantaClient.<init>(MantaClient.java:193)
	at com.joyent.invaliduser.InvalidUserApplication.main(InvalidUserApplication.java:28)

Process finished with exit code 0
```
It seems an Invalid MantaUser no longer results in ```500 Internal Server Error```. So we can safely close the aforementioned issue. Instead a ```ConfigurationException``` is generally raised which has been incorporated since ```3.0.0``` [here ](https://github.com/joyent/java-manta/blob/master/java-manta-client-unshaded/src/main/java/com/joyent/manta/exception/ConfigurationException.java) within this context even if I haven't caught the runtime exception being raised and would have printed out: 
```
com.joyent.manta.exception.ConfigurationException: Errors when loading Manta SDK configuration:
Manta key id must be specified
``` 
under normal circumstances.

**Comment by nairashwin952013** [comment]
Also notify me if we need to test this issue since it can be potentially added as a unit-test ?

**Comment by nairashwin952013** [comment]
Should I include it within the integration-test ```MantaClientIT``` or ```MantaClientPutIT``` ?

**Comment by dekobon** [comment]
MantaClientIT or make a new class called  MantaClientAuthenticationIT.

**Comment by nairashwin952013** [comment]
Referenced Pull request verifies issue can be closed.
