### ISSUE TITLE
Cryptographic authentication errors when using SDK with COSBench

### ISSUE THREAD

**Issue by dekobon** [joyent/java-manta#213]
**Problem**
When using the Java Manta SDK in COSBench in client-side encryption mode, approximately 5% of all GET requests fail their ciphertext authenticity check. This is currently happening in development builds of [COSBench Manta](https://github.com/joyent/cosbench-manta) using the 3.0 branch of the Java Manta SDK.

**Reproduction Steps**
1. Start the COSBench driver and controller (with the Java Manta SDK installed.
2. Visit the controller port (assuming Linux localhost docker mapping - e.g. [http://localhost:19088/controller/](http://localhost:19088/controller/)).
3. Navigate to the submit workload page, then submit this workload:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<workload name="manta-encrypted-sample" description="sample benchmark for manta">
  <storage type="manta" config="manta.verify_uploads=false;retries=0;manta.client_encryption=true;manta.encryption_key_id=cosbench-test;manta.encryption_algorithm=AES128/CTR/NoPadding;manta.encryption_key_bytes_base64=MKBUne726xyvMK2P0Y2DXg==;"/>
  <workflow>
<!-- Work Thread : 16 -->
    <workstage name="I016-8kb">
      <work type="init"    workers="1" config="cprefix=b100;containers=r(1,1)" />
    </workstage>
    <workstage name="P016-8kb">
      <work type="prepare" workers="1" config="cprefix=b100;containers=r(1,1);objects=r(1,100);sizes=c(8)KB" />
    </workstage>
    <workstage name="M016-8kb">
      <work name="main" workers="16" runtime="120">
        <operation type="read"  ratio="100" config="cprefix=b100;containers=u(1,1);objects=u(1,100)" />
      </work>
    </workstage>
    <workstage name="C016-8kb">
      <work type="cleanup" workers="1" config="cprefix=b100;containers=r(1,1);objects=r(1,100)" />
    </workstage>
    <workstage name="D016-8kb">
      <work type="dispose" workers="1" config="cprefix=b100;containers=r(1,1)" />
    </workstage>
  </workflow>
</workload>
```
4. Now, monitor the file lob/system.log:
```
tomcat@b92ca10ae93a:~$ tail -f li
... a bunch of logs
... then the errors
2017-02-05 23:28:18,213 [ERROR] [AbstractAgent] - unexpected exception
com.joyent.manta.exception.MantaClientEncryptionCiphertextAuthenticationException: Stored authentication HMAC failed to validate ciphertext. Stored authentication HMAC failed to validate ciphertext.
Exception Context:
	[1:path=/elijah.zupancic/stor/cosbench/b1001/myobjects71]
	[2:etag=15317c1e-f2d3-cd52-855d-c3bc1fd45401]
	[3:lastModified=Sun Feb 05 23:27:52 UTC 2017]
	[4:ciphertextContentLength=8016]
	[5:plaintextContentLength=8000]
	[6:plaintextBytesRead=8000]
	[7:cipherId=AES128/CTR/NoPadding]
	[8:cipherDetails=com.joyent.manta.client.crypto.AesCtrCipherDetails@34b75558[hmacAlgorithm=HmacMD5,authenticationTagOrHmacLength=16,keyLengthBits=128,cipherId=AES128/CTR/NoPadding,cipherAlgorithmJavaName=AES/CTR/NoPadding,isAEADCipher=false]]
	[9:cipherInputStream=org.bouncycastle.jcajce.io.CipherInputStream@446f6f10]
	[10:authenticationEnabled=true]
	[11:threadName=pool-4-thread-9]
	[12:iv=44739f88dbe6b298c44c5f846b045fb9]
	[13:hmacAlgorithm=HmacMD5]
	[14:expected=c6d6dc388090a9f2fa7b30b0a5a7d707]
	[15:checksum=a8aacef7225f7fe99898fea7a2962723]
---------------------------------
	at com.joyent.manta.client.crypto.MantaEncryptedObjectInputStream.close(MantaEncryptedObjectInputStream.java:717)
	at org.apache.commons.io.IOUtils.closeQuietly(IOUtils.java:178)
	at com.intel.cosbench.driver.operator.Reader.doRead(Reader.java:107)
	at com.intel.cosbench.driver.operator.Reader.operate(Reader.java:69)
	at com.intel.cosbench.driver.operator.AbstractOperator.operate(AbstractOperator.java:76)
	at com.intel.cosbench.driver.agent.WorkAgent.performOperation(WorkAgent.java:197)
	at com.intel.cosbench.driver.agent.WorkAgent.doWork(WorkAgent.java:177)
	at com.intel.cosbench.driver.agent.WorkAgent.execute(WorkAgent.java:134)
	at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:44)
	at com.intel.cosbench.driver.agent.AbstractAgent.call(AbstractAgent.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
The code executing the SDK is relatively simple: https://github.com/joyent/cosbench-manta/blob/1.1.0/src/main/java/com/joyent/manta/cosbench/MantaStorage.java#L284
You only need to worry about the code path highlighted because it isn't configured to do range requests in the workload above.

**Debugging**

If you modify the driver startup script to invoke java with these flags:
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005

And you setup docker to expose port 5005 you can actually hook up a debugger and step through the code. I did so but was totally unable to figure out where the HMAC calculation was going awry.
I have added the following tests to attempt to isolate the issue but all of them pass (both in encrypted and in unencrypted modes):
```
    canReadStreamAndThenCloseWithoutErrors
    canCopyStreamToFileAndCloseWithoutErrors
    canCreateStreamInOneThreadAndCloseInAnother
    canCopyStreamWithLargeBufferBufferAuthenticatedAes* (they all run the linked method)
```

My thoughts about what to do next was that I would need to build an integration test that ran 16 concurrent threads downloading in encrypted mode. However, I tried that level of concurrency using our homegrown [SDK benchmark utility](https://github.com/joyent/java-manta/blob/server-side-mpu/java-manta-benchmark/src/main/java/com/joyent/manta/benchmark/Benchmark.java).
I tried with a concurrency level of 16 and with 8k files in encrypted mode and didn't once see the error.

Also, I did some additional analysis of the files that were failing their HMAC check in COSBench. I was able to pause COSBench before it deleted the test workload. I then ran the SDK's CLI utility and used it to download and decrypt the files from Manta. It did it with no problems using the exact same code path inside the SDK as COSBench.

Additionally, I set up a thread name logger on every method with the [MantaStorage](https://github.com/joyent/cosbench-manta/blob/master/src/main/java/com/joyent/manta/cosbench/MantaStorage.java) class and determined that all access of the underlying SDK was done always using the same thread, so I was able to rule out serial thread safety (unsafety?) issues.

Really at this point, I'm a bit lost. I can observe the problem happening real time in the debugger, but I have no idea why the HMAC is being calculated differently. If it is any consolation, the same behavior happens in an entirely different distribution of the JDK running on a different OS (Linux Azul JDK vs OS X Oracle JDK). I haven't even tested on a LX branded zone because of these problems happening natively on Linux/OS X.

**Comment by cburroughs** [comment]
Is this still an issue with a released version? @douglasAtJoyent have you run into anything like this

**Comment by dekobon** [comment]
This has been fixed with the latest release of cosbench-manta that upgrades to the latest Java Manta SDK.
