### ISSUE TITLE
some MantaClient.put paths skip url-encoding

### ISSUE THREAD

**Issue by cburroughs** [joyent/java-manta#230]
ex, for a `File`:

```
 $ java -jar java-manta-cli/target/java-manta-cli-3.0.1-SNAPSHOT-jar-with-dependencies.jar put-file /tmp/hi '/cburroughs/stor/tmp/!@#$%^&*()'
14:57:28.839 [main] DEBUG com.joyent.manta.client.crypto.ExternalSecurityProviderLoader - Bouncy Castle provider was not loaded, adding to providers
14:57:28.843 [main] DEBUG com.joyent.manta.client.MantaClient - Preferred Security Provider: BC version 1.56
14:57:29.154 [main] DEBUG com.joyent.manta.http.StandardHttpHelper - PUT    /cburroughs/stor/tmp/!@#$%^&*()
14:57:29.161 [main] DEBUG com.joyent.manta.org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection manager is shutting down
14:57:29.162 [main] DEBUG com.joyent.manta.org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection manager shut down
Malformed escape pair at index 57: https://us-east.manta.joyent.com/cburroughs/stor/tmp/!@#$%^&*()
java.lang.IllegalArgumentException: Malformed escape pair at index 57: https://us-east.manta.joyent.com/cburroughs/stor/tmp/!@#$%^&*()
	at java.net.URI.create(URI.java:852)
	at com.joyent.manta.org.apache.http.client.methods.HttpPut.<init>(HttpPut.java:65)
	at com.joyent.manta.http.MantaConnectionFactory.put(MantaConnectionFactory.java:602)
	at com.joyent.manta.http.StandardHttpHelper.httpPut(StandardHttpHelper.java:177)
	at com.joyent.manta.client.MantaClient.put(MantaClient.java:1216)
	at com.joyent.manta.client.MantaClient.put(MantaClient.java:1146)
	at com.joyent.manta.cli.MantaCLI.putFile(MantaCLI.java:282)
	at com.joyent.manta.cli.MantaCLI.main(MantaCLI.java:104)
Caused by: java.net.URISyntaxException: Malformed escape pair at index 57: https://us-east.manta.joyent.com/cburroughs/stor/tmp/!@#$%^&*()
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.scanEscape(URI.java:2978)
	at java.net.URI$Parser.scan(URI.java:3001)
	at java.net.URI$Parser.checkChars(URI.java:3019)
	at java.net.URI$Parser.parse(URI.java:3067)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 7 more
```

**Comment by cburroughs** [comment]
A subtle bit of related fallout is that this means that MantaObject has sometimes been returning an encoded path, and sometimes and un-encoded one.  I think the least surprising thing would be to always return the same thing the user thought they asked for.
