### ISSUE TITLE
MPU status-related tests failing 

### ISSUE THREAD

**Issue by tjcelaya** [joyent/java-manta#268]
The following three test methods are failing:

- com.joyent.manta.client.multipart.EncryptedServerSideMultipartManagerIT#canAbortUpload

```
  java.lang.AssertionError: MPU is not in an aborted or aborting status. Actual status: UNKNOWN

    at org.testng.Assert.fail(Assert.java:94)
    at com.joyent.manta.client.multipart.EncryptedServerSideMultipartManagerIT.canAbortUpload(EncryptedServerSideMultipartManagerIT.java:109)
```
- com.joyent.manta.client.multipart.EncryptedServerSideMultipartManagerIT#canGetPart
```
  com.joyent.manta.exception.MantaMultipartException: Expected response field was missing or malformed
  Exception Context:
    [1:mantaSdkVersion=3.0.0-SNAPSHOT]
    [2:requestId=a82e57eb-57a1-11e7-9f7b-f132c1bbfa44]
    [3:request=HttpGet[version=<null>,uri=https://us-east.manta.samsungcloud.io/tomas.celaya/uploads/7/7e0fc5f6-7d24-e8cb-effa-d1611cfd8a50/state,config=<null>,aborted=false,cancellableRef=org.apache.http.impl.execchain.ConnectionHolder@65e21ce3,headergroup=[],params=org.apache.http.params.BasicHttpParams@2aff9dff]]
    [4:requestMethod=GET]
    [5:requestURL=https://us-east.manta.samsungcloud.io/tomas.celaya/uploads/7/7e0fc5f6-7d24-e8cb-effa-d1611cfd8a50/state]
    [6:requestHeaders=]
    [7:loadBalancerAddress=148.78.5.213]
    [8:response=HttpResponseProxy[original=HTTP/1.1 200 OK [Content-Type: application/json, Content-Length: 671, Content-MD5: GgT1nyPI59qTx5h/KzozwQ==, Date: Thu, 22 Jun 2017 23:22:28 GMT, Server: Manta, x-request-id: a82e57eb-57a1-11e7-9f7b-f132c1bbfa44, x-response-time: 5, x-server-name: c14c1fb8-8446-45fb-b557-df98395f7320, Connection: keep-alive] ResponseEntityProxy{[Content-Type: application/json,Content-Length: 671,Chunked: false]},connHolder=org.apache.http.impl.execchain.ConnectionHolder@65e21ce3]]
    [9:responseHeaders=Content-Type: application/json, Content-Length: 671, Content-MD5: GgT1nyPI59qTx5h/KzozwQ==, Date: Thu, 22 Jun 2017 23:22:28 GMT, Server: Manta, x-request-id: a82e57eb-57a1-11e7-9f7b-f132c1bbfa44, x-response-time: 5, x-server-name: c14c1fb8-8446-45fb-b557-df98395f7320, Connection: keep-alive]
    [10:responseStatusCode=200]
    [11:responseStatusReason=OK]
  ---------------------------------

    at com.joyent.manta.client.multipart.ServerSideMultipartManager.getPart(ServerSideMultipartManager.java:378)
    at com.joyent.manta.client.multipart.ServerSideMultipartManager.getPart(ServerSideMultipartManager.java:67)
    at com.joyent.manta.client.multipart.EncryptedMultipartManager.getPart(EncryptedMultipartManager.java:326)
    at com.joyent.manta.client.multipart.EncryptedServerSideMultipartManagerIT.canGetPart(EncryptedServerSideMultipartManagerIT.java:178)

  Caused by: java.lang.NullPointerException: Unable to read object path from response
    at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
    at com.joyent.manta.client.multipart.ServerSideMultipartManager.getPart(ServerSideMultipartManager.java:368)
    ... 26 more
```
- com.joyent.manta.client.multipart.EncryptedServerSideMultipartManagerIT#canGetStatus
```
java.lang.AssertionError: MPU com.joyent.manta.client.multipart.ServerSideMultipartUpload@151bf776[id=3bdbbf90-5096-e68a-fe34-d81915faf78f,path=/tomas.celaya/stor/java-manta-integration-tests/16c93e5e-d580-4822-a127-426d969f43d85cd108d2-8e2a-481f-820d-d735bcb7e636,partsDirectory=/tomas.celaya/uploads/3/3bdbbf90-5096-e68a-fe34-d81915faf78f]in invalid status after complete invocation. Actual status: UNKNOWN

    at org.testng.Assert.fail(Assert.java:94)
    at com.joyent.manta.client.multipart.EncryptedServerSideMultipartManagerIT.canGetStatus(EncryptedServerSideMultipartManagerIT.java:162)
```

**Comment by cburroughs** [comment]
Do we know which commit they began failing on?

**Comment by tjcelaya** [comment]
Not sure, these integration tests aren't run as part of Travis-CI so it's hard to figure out when the regression occurred. Inspecting some of the issues further the specification of state transitions was committed to rfd#65 since [this commit](https://github.com/joyent/rfd/commit/8f190fd031dcfa46c6ce8cd18f5b6b7f12545704) so it's been quite a while.
