### ISSUE TITLE
MantaClientPutIT#testPutWithJPGFile failures on LX ubuntu instance

### ISSUE THREAD

**Issue by cburroughs** [joyent/java-manta#276]
On an instance like so:

```
# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
# uname -a
Linux cf5b8960-613e-c7e2-f6cb-97c615bc8a06 4.3.0 BrandZ virtual linux x86_64 x86_64 x86_64 GNU/Linux
# java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

I am seeing consistent failures at:
```
(com.joyent.manta.client.MantaClientPutIT)  Time elapsed: 0.177 sec  <<< FAILURE!
java.lang.AssertionError: Content type wasn't detected correctly expected [image/jpeg] but found [text/plain]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:513)
        at org.testng.Assert.assertEqualsImpl(Assert.java:135)
        at org.testng.Assert.assertEquals(Assert.java:116)
        at org.testng.Assert.assertEquals(Assert.java:190)
        at com.joyent.manta.client.MantaClientPutIT.testPutWithJPGFile(MantaClientPutIT.java:333)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
        at org.testng.TestRunner.privateRun(TestRunner.java:782)
        at org.testng.TestRunner.run(TestRunner.java:632)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
        at org.testng.SuiteRunner.run(SuiteRunner.java:268)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
        at org.testng.TestNG.run(TestNG.java:1064)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

This is because in `ContentTypeLookup` is calling `Files.probeContentType(file.toPath())` which is retuning `text/plain`.  I don't have this issue on a Debian workstation, and `file` returns the expected result.  I'm not sure what is at fault.  The javadocs for that method do say "The means by which this method determines the file type is highly implementation specific". (`URLConnection.guessContentTypeFromName` gets it correct.)

I'm not sure how to proceed:
 (A) Figure out what exactly is different on the LX.  Since `file` returns the correct answer, this seems unlikely to be a platform or image bug .  I think my setup is a reasonable one that should work without a configuration 'gotcha'.
 (B) Set the Content-Type explicitly in the test.  This is the smallest change to get to green, but I feel that it papers over the intent of a test about uploading jpegs.  Notably no unit tests otherwise exposed the issue.
 (C) Change `findOrDefaultContentType` to prefer other heuristics over `probeContentType`.  For example, `javax.activation.MimetypesFileTypeMap` happens to get this right.  I am also unsure why the two `findOrDefaultContentType`  orders the source/destination checks the way it does.
 (D) Use something like Apache Tika to do this more robustly by peeking at the bytes in the stream.  I think that is too big a change and not worth adding dependencies.

**Comment by cburroughs** [comment]
After sitting like this for a few days, I'm leaning towards starting down the (C) road.

**Comment by cburroughs** [comment]
So, this is not the JDK at its best and `Files.probeContentType`, `MimetypesFileTypeMap`, and `URLConnection` share basically no code in common.  

`MimetypesFileTypeMap` & `URLConnection` are relatively old classes full of gems like 

```
// REMIND add exception handling...
```
```
        int dot_pos = filename.lastIndexOf("."); // period index
```
```
        try {
            DB[PROG] = new MimeTypeFile(is);
        } catch (IOException ex) {
            // XXX - really should throw it
        }
```
And `FileTypeMap` isn't actually a `Map`.

`MimetypesFileTypeMap` works by reading mime-type files from a per-defined set of places including `$HOME`, within `JAVA_HOME`, or a [hard coded bundle](https://github.com/dmlloyd/openjdk/blob/jdk8u/jdk8u/jaxws/src/share/jaf_classes/META-INF/mimetypes.default).  At least on Debian & Ubuntu, it looks like a `mime.types` is no longer shipped in `JAVA_HOME` since Java 8, so really this is just looking at a very small file that happens to include `image/jpeg`.

`URLConnection` uses a `MimeTable` which in turn reads from a `content-types.properties` file bundled with the jre.  It is basically a normal mime types file, but hand rolled into properties format.

`Files.probeContentType` is more complicated.  It magically chains together OS specific providers (Linux, Aix, Windows, etc.) with levels of  confounding indirection one would expect from modern Java.  For example, on Linux this does

```java
    FileTypeDetector getFileTypeDetector() {
        Path userMimeTypes = Paths.get(AccessController.doPrivileged(
            new GetPropertyAction("user.home")), ".mime.types");
        Path etcMimeTypes = Paths.get("/etc/mime.types");

        return chain(new GnomeFileTypeDetector(),
                     new MimeTypesFileTypeDetector(userMimeTypes),
                     new MimeTypesFileTypeDetector(etcMimeTypes),
                     new MagicFileTypeDetector());
    }
```

The most interesting one is `GnomeFileTypeDetector`.  Some terribly ugly code aded to `ContentTypeLookup` can show what is going on:

```java
        System.out.println("?????????????????????");
        System.out.println(headerContentType);
        System.out.println(Files.probeContentType(file.toPath()) + " " +  file.getCanonicalPath());
        System.out.println(new MimetypesFileTypeMap().getContentType(file.getName()));
        System.out.println(URLConnection.guessContentTypeFromName(filename));
        System.out.println(URLConnection.guessContentTypeFromName(file.getName()));
        System.out.println("What is Files.probe... doing??");
        System.out.println(new sun.nio.fs.GnomeFileTypeDetector().probeContentType(file.toPath()));
        try {
            java.lang.Class cls = null;
            java.lang.reflect.Constructor constructor = null;
            Object obj = null;
            java.lang.reflect.Method m = null;

            cls = Class.forName("sun.nio.fs.MimeTypesFileTypeDetector");
            constructor = cls.getDeclaredConstructor(java.nio.file.Path.class);
            constructor.setAccessible(true);
            obj = constructor.newInstance(java.nio.file.Paths.get("/root/.mime.types"));
            m = cls.getMethod("probeContentType", java.nio.file.Path.class);
            System.out.println(m.invoke(obj, file.toPath()));

            cls = Class.forName("sun.nio.fs.MimeTypesFileTypeDetector");
            constructor = cls.getDeclaredConstructor(java.nio.file.Path.class);
            constructor.setAccessible(true);
            obj = constructor.newInstance(java.nio.file.Paths.get("/etc/mime.types"));
            m = cls.getMethod("probeContentType", java.nio.file.Path.class);
            System.out.println(m.invoke(obj, file.toPath()));

            cls = Class.forName("sun.nio.fs.MagicFileTypeDetector");
            constructor = cls.getDeclaredConstructor();
            constructor.setAccessible(true);
            obj = constructor.newInstance();
            m = cls.getMethod("probeContentType", java.nio.file.Path.class);
            System.out.println(m.invoke(obj, file.toPath()));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
```


which on my nice ubuntu CI agent results in:
```
Running com.joyent.manta.client.MantaClientPutIT
?????????????????????
null
text/plain /tmp/upload5436138932975992340.jpg
image/jpeg
null
image/jpeg
What is Files.probe... doing??
text/plain
null
image/jpeg
image/jpeg
```

So we can see that `GnomeFileTypeDetector` is the one at fault.  `GnomeFileTypeDetector` uses a combination of gnome-vfs (deprecated since 2008!?) and [libgio](https://en.wikipedia.org/wiki/GIO_%28software%29).  In [JDK9](https://bugs.openjdk.java.net/browse/JDK-8129633) the deprecated code is finally removed and it just uses libgio.  I can reproduce a similar issue by pointing libgio at an empty file on ubuntu

```
root@b521c6ac-c09d-6679-dfb3-ddd63b36e2bf:/# touch /tmp/empty.jpeg
root@b521c6ac-c09d-6679-dfb3-ddd63b36e2bf:/# python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys,gio
>>> f = gio.File('/tmp/empty.jpeg')
>>> info = f.query_info('standard::content-type')
>>> print info.get_content_type()
text/plain
```

but adding a `flush` to `testPutWithJPGFile` (so the tmp file should not be empty) does not resolve the issue.  Removing `libgio.so` causes `GnomeFileTypeDetector` to return `null` instead of `text/plain`.  None of this clears up why I am seeing the issue on Ubuntu but not Debian (I tried in LX and KVM), but "Don't use Ubuntu" is not satisfactory advice.

Since I can't figure out the exact repro case outside of the test, I have not opened anything with any upstream.

I think the ideal solution would be to to just not use the `GnomeFileTypeDetector` because everything else `Files.probeContentType` does seems reasonable.  However, most of the relevant classes are non-standard private ones and I don't see any reasonable way to perform the surgery that without reams of reflection code that will almost certainly introduce errors on some obscure (aka not Linux) platforms and risk problems in future JDKs.  I had hopes for `MimetypesFileTypeMap`, but it looks like in practice  post-java8 that is just a list of about 20 file types.  I think at this point the smallest safe fix is to re-order the checks so that we do `Files.probeContentType` *last* in the `firstNonNull` series.  That way we still take advantage of all of `/etc/mime.types` and libmagic for obscure types, but sidestep the "we can't actually trust this class to return `null`" problem.

**Comment by cburroughs** [comment]
With the latest changes, these tests now pass in the in-progress CI environment.
