### ISSUE TITLE
503 response on smaller-than-minimum-sized MPU part (or during complete) causes IOException

### ISSUE THREAD

**Issue by tjcelaya** [joyent/java-manta#297]
Running `EncryptedServerSideMultipartManagerIT#canRetryUploadPart` with Charles Web Proxy rewriting response code of the final part triggers the exception attached below. Unfortunately `EncryptionStateRecorder` does not provide a straightforward way to handle this situation so this fix will be more complicated. Snapshots might need to include streams instead of just the `Cipher` and `HMac` objects:

```
java.io.IOException: write(-103) failed: stream is closed

	at org.apache.commons.io.output.ClosedOutputStream.write(ClosedOutputStream.java:48)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.OutputStream.write(OutputStream.java:75)
	at org.apache.commons.io.output.ProxyOutputStream.write(ProxyOutputStream.java:72)
	at org.bouncycastle.jcajce.io.CipherOutputStream.write(Unknown Source)
	at com.joyent.manta.util.HmacOutputStream.write(HmacOutputStream.java:74)
	at org.apache.commons.io.output.ProxyOutputStream.write(ProxyOutputStream.java:90)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2147)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102)
	at com.joyent.manta.client.crypto.EncryptingPartEntity.writeTo(EncryptingPartEntity.java:134)
	at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:121)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:160)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.joyent.manta.client.multipart.ServerSideMultipartManager.uploadPart(ServerSideMultipartManager.java:330)
	at com.joyent.manta.client.multipart.ServerSideMultipartManager.uploadPart(ServerSideMultipartManager.java:68)
	at com.joyent.manta.client.multipart.EncryptedMultipartManager.uploadPart(EncryptedMultipartManager.java:290)
	at com.joyent.manta.client.multipart.EncryptedMultipartManager.uploadPart(EncryptedMultipartManager.java:46)
	at com.joyent.manta.client.multipart.AbstractMultipartManager.uploadPart(AbstractMultipartManager.java:115)
	at com.joyent.manta.client.multipart.EncryptedServerSideMultipartManagerIT.canRetryUploadPart(EncryptedServerSideMultipartManagerIT.java:521)
```

**Comment by cburroughs** [comment]
Is this retried cleanly in cases that don't involve CSE? I don't think java-manta should be obligated to retry in every possible case, and clients have to handle errors getting past back to them eventually anyway.

**Comment by tjcelaya** [comment]
This is actually a failure on my part to cover this situation when working
on 3.1.4 and 3.1.5.
EncryptedServersideMultipartManagerIT#canRetryUploadPart simulates a
network failure and the latest PR that was merged disables automatic
retries entirely for MPU+CSE.

This issue is about the fact that EncryptingPartEntity triggers the
LastPartCallback and finalizes the MPU but since the response is a 503 the
user *can't* retry because remainderAndLastPartAuth closed the
CipherOutputStream.

**Comment by tjcelaya** [comment]
Discovered that encryption state can also be finalized during MPU complete. This will need more tests..

**Comment by tjcelaya** [comment]
Instead of attempting to write a test for encryption state rewind occurring during complete (because of shading) I'm opting to write a test that an exception during a call to `complete` with a `FailingInputStream` does successfully rewind. We still rely on invalid response codes to bubble up the same way network errors bubble up so this covers both scenarios.
