### ISSUE TITLE
non-empty path validation would result in clearer error messages

### ISSUE THREAD

**Issue by cburroughs** [joyent/java-manta#303]
Passing the empty string as a path results in a rather unhelpful error message.  I think we could safely validate both that the path is non-null, and non-empty.

```
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_131]
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[na:1.8.0_131]
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023) ~[na:1.8.0_131]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125) ~[na:1.8.0_131]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[na:1.8.0_131]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403) ~[na:1.8.0_131]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387) ~[na:1.8.0_131]
        at com.joyent.manta.org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:
396) ~[foo-0.0.0-SNAPSHOT.jar:na]
        at com.joyent.manta.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355) ~
[foo-0.0.0-SNAPSHOT.jar:na]
        at com.joyent.manta.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperato
r.java:142) ~[foo-0.0.0-SNAPSHOT.jar:na]
        at com.joyent.manta.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.
java:359) ~[foo-0.0.0-SNAPSHOT.jar:na]
        at com.joyent.manta.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[scloud-cse-verif
ier-0.0.0-SNAPSHOT.jar:na]
        at com.joyent.manta.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[foo-0.0
.0-SNAPSHOT.jar:na]
        at com.joyent.manta.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[foo-0.0.0-S
NAPSHOT.jar:na]
        at com.joyent.manta.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[foo-0.0.0-SNAPSHOT
.jar:na]
        at com.joyent.manta.org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85) 
~[foo-0.0.0-SNAPSHOT.jar:na]
        at com.joyent.manta.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[foo-0.0.0-S
NAPSHOT.jar:na]
        at com.joyent.manta.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[scloud-cse-verif
ier-0.0.0-SNAPSHOT.jar:na]
        at com.joyent.manta.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[scloud-cse-verifi
er-0.0.0-SNAPSHOT.jar:na]
        at com.joyent.manta.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[scloud-cse-verif
ier-0.0.0-SNAPSHOT.jar:na]
        at com.joyent.manta.http.StandardHttpHelper.executeRequest(StandardHttpHelper.java:495) ~[foo-0.0.0-SNAPSHOT
.jar:na]
        at com.joyent.manta.http.StandardHttpHelper.httpRequestAsInputStream(StandardHttpHelper.java:332) ~[foo-0.0.
0-SNAPSHOT.jar:na]
        at com.joyent.manta.http.EncryptionHttpHelper.httpRequestAsInputStream(EncryptionHttpHelper.java:280) ~[foo-
0.0.0-SNAPSHOT.jar:na]
        at com.joyent.manta.client.MantaClient.getAsInputStream(MantaClient.java:408) 
```

**Comment by dekobon** [comment]
:+1:

**Comment by cburroughs** [comment]
When I wrote this ticket I assumed that we were validating `null`, but ought to add the empty string.  That is true for most other methods, but in this particular case we are *also* missing the `null`  check.

```
 public MantaObjectInputStream getAsInputStream(final String rawPath,
                                                   final MantaHttpHeaders requestHeaders)
            throws IOException {
        final String path = formatPath(rawPath);
        final HttpGet get = connectionFactory.get(path);

        MantaObjectInputStream stream = httpHelper.httpRequestAsInputStream(get,
                requestHeaders);

        danglingStreams.add(stream);

        return stream;
    }
```

In a handful of cases we are using the slightly stricter `notBlank` (which disallows "" and " ").  I don't see anything in the git history for why that was sometimes chosen.

**Comment by dekobon** [comment]
`notBlank` is my doing. For better or worse, I was trying to move everything that I touched to a stricter validation. I never took it on to globally make everything consistent. It might be a good idea to do that.
