### ISSUE TITLE
JMeter extension failing when using 3.2.0

### ISSUE THREAD

**Issue by douglasAtJoyent** [joyent/java-manta#376]
When updating to 3.2.0, the JMeter extension I get exceptions.

```
2017/11/16 12:07:16 ERROR - jmeter.threads.JMeterThread: Error while processing sampler 'Verify Upload' : com.joyent.manta.http.signature.CryptoException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: SHA256withNativeRSA, provider: native-rsa, class: com.joyent.manta.http.signature.crypto.NativeRSAWithSHA$SHA256)
	at com.joyent.manta.http.signature.Signer.<init>(Signer.java:123)
	at com.joyent.manta.http.signature.Signer$Builder.build(Signer.java:631)
	at com.joyent.manta.http.signature.ThreadLocalSigner.initialValue(ThreadLocalSigner.java:80)
	at com.joyent.manta.http.signature.ThreadLocalSigner.initialValue(ThreadLocalSigner.java:22)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at com.joyent.manta.http.signature.apache.httpclient.HttpSignatureAuthScheme.signRequestHeader(HttpSignatureAuthScheme.java:198)
	at com.joyent.manta.http.signature.apache.httpclient.HttpSignatureAuthScheme.authenticate(HttpSignatureAuthScheme.java:161)
	at com.joyent.manta.http.DynamicHttpSignatureRequestInterceptor.process(DynamicHttpSignatureRequestInterceptor.java:53)
	at com.joyent.manta.http.MantaHttpRequestFactory.prepare(MantaHttpRequestFactory.java:215)
	at com.joyent.manta.http.MantaHttpRequestFactory.get(MantaHttpRequestFactory.java:118)
	at com.joyent.manta.client.MantaClient.getAsInputStream(MantaClient.java:482)
	at com.joyent.manta.client.MantaClient.getAsInputStream(MantaClient.java:521)
	at com.joyent.jmetersampler.AtomicClientDownload.runTest(AtomicClientDownload.java:36)
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:196)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:475)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:418)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:249)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: SHA256withNativeRSA, provider: native-rsa, class: com.joyent.manta.http.signature.crypto.NativeRSAWithSHA$SHA256)
	at java.security.Provider$Service.newInstance(Provider.java:1617)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:218)
	at java.security.Signature.getInstance(Signature.java:405)
	at com.joyent.manta.http.signature.Signer.<init>(Signer.java:121)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: com/squareup/jnagmp/GmpInteger
	at com.joyent.manta.http.signature.crypto.NativeRSABlindedEngine.<init>(NativeRSABlindedEngine.java:58)
	at com.joyent.manta.http.signature.crypto.NativeRSAWithSHA$SHA256.<init>(NativeRSAWithSHA.java:75)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.security.Provider$Service.newInstance(Provider.java:1595)
	... 22 more
Caused by: java.lang.ClassNotFoundException: com.squareup.jnagmp.GmpInteger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more
```

**Comment by tjcelaya** [comment]
Shading-related confusion is causing this. This won't be reproducible when running jmeter through maven because maven would resolve the dependency in `JMeterMantaExtension`. I forgot the extension used to depend on the `java-manta-benchkmark` module which did its own shading.
