### ISSUE TITLE
Manta client unable to set new connection timeout

### ISSUE THREAD

**Issue by nairashwin952013** [joyent/java-manta#441]
- **Description**: Manta Client-Java SDK v3.2.5. The bug occurred in the java-manta-client sub-module within the java-manta main module. The expected result for the simulated bug conditions should be a Connection Failure caused by an Exception raised due to a connection timeout. The actual result received is a request made to a valid path like ```HEAD = "/MANTA_USER/stor/anyObject"``` without any **timeout exception**.

- **Replicate Bug & Environment Variables:**
    * Firstly configure MANTA_URL to an invalid value/network path. Some random web address where   Manta isn't deployed.[https://example952013.com](url).
    * Set MANTA_TIMEOUT = 5000 (manta.timeout) & MANTA_HTTP_RETRIES = 3 (manta.retries).
    * Other Timeout parameters are set to default. Refer [https://github.com/joyent/java-manta/blob/master/USAGE.md#configuration](url).
    * Run any Unit Tests/ITs testing the Manta Client or do a head request to a valid path mentioned in   Description.

- **Analysis**: The bug has been observed due to confusion between multiple timeout parameters ''' ISSUE#109'''. Intial understanding to the problem requires proper resolution of definitions/declarations between all Timeout parameters. This includes interpreting whether overriding has occurred like ``` ISSUE#377```. 

- **Resolution/Verification**: Make a new Test class with additional timeout settings and ```MANTA_TCP_SOCKET_TIMEOUT```applied, new documentation explaining the changes and ensuring similar errors don't occur in the future with proper design improvements.

**Comment by nairashwin952013** [comment]
```
STACK TRACE FOR ISSUE #441
[main] DEBUG com.joyent.manta.client.MantaClient - PUT    /MANTA_USER/stor/java-manta-integration-tests [directory]
[main] DEBUG com.joyent.http.signature.apache.httpclient.HttpSignatureAuthScheme - Signing request: PUT https://example952013.com/MANTA_USER/stor/java-manta-integration-tests HTTP/1.1
[main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://example952013.com:443][total kept alive: 0; route allocated: 0 of 24; total allocated: 0 of 24]
[main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection leased: [id: 12][route: {s}->https://example952013.com:443][total kept alive: 0; route allocated: 1 of 24; total allocated: 1 of 24]
[main] DEBUG org.apache.http.impl.execchain.MainClientExec - Opening connection {s}->https://example952013.com:443
[main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-12: Shutdown connection
[main] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection discarded
[main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 12][route: {s}->https://example952013.com:443][total kept alive: 0; route allocated: 0 of 24; total allocated: 0 of 24]
[main] DEBUG com.joyent.manta.http.MantaHttpRequestRetryHandler - Request failed, unable to retry.
java.net.UnknownHostException: example952013.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at com.joyent.manta.http.ShufflingDnsResolver.resolve(ShufflingDnsResolver.java:27)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.joyent.manta.http.StandardHttpHelper.executeRequest(StandardHttpHelper.java:629)
	at com.joyent.manta.http.StandardHttpHelper.executeAndCloseRequest(StandardHttpHelper.java:615)
	at com.joyent.manta.client.MantaClient.putDirectory(MantaClient.java:1681)
	at com.joyent.manta.client.RecursiveDirectoryCreationStrategy.createCompletely(RecursiveDirectoryCreationStrategy.java:71)
	at com.joyent.manta.client.MantaClient.putDirectory(MantaClient.java:1727)
	at com.joyent.manta.client.MantaClient.putDirectory(MantaClient.java:1699)
	at com.joyent.manta.client.jobs.MantaClientJobIT.beforeClass(MantaClientJobIT.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

java.net.UnknownHostException: example952013.com

	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at com.joyent.manta.http.ShufflingDnsResolver.resolve(ShufflingDnsResolver.java:27)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.joyent.manta.http.StandardHttpHelper.executeRequest(StandardHttpHelper.java:629)
	at com.joyent.manta.http.StandardHttpHelper.executeAndCloseRequest(StandardHttpHelper.java:615)
	at com.joyent.manta.client.MantaClient.putDirectory(MantaClient.java:1681)
	at com.joyent.manta.client.RecursiveDirectoryCreationStrategy.createCompletely(RecursiveDirectoryCreationStrategy.java:71)
	at com.joyent.manta.client.MantaClient.putDirectory(MantaClient.java:1727)
	at com.joyent.manta.client.MantaClient.putDirectory(MantaClient.java:1699)
	at com.joyent.manta.client.jobs.MantaClientJobIT.beforeClass(MantaClientJobIT.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

**Comment by nairashwin952013** [comment]
Shall I close the issue?

**Comment by dekobon** [comment]
Yes.
